---
title: "Projekt nr.2"
author: "Olga Sieradzan i Aleksandra Węgrzyn"
date: "2024-01-09"
output:
   html_document:
    toc: true
    toc_float: 
      smooth_scrool: true
    df_print: paged
    theme: united
---

```{r,echo = FALSE, message = FALSE, warning = FALSE}
# Pobieranie danych z pliku csv, wszytskie dane zostały pobrane ze strony stooq.pl

eat_w <- read_csv("~/eat_w.csv") # Tygodniowe dane AmRest Holdings SE mWIG40

cdr_d <- read_csv("~/cdr_d.csv") # Dzienne dane CDPROJECT WIG20
cdr_w <- read_delim("~/cdr_w.csv", delim = ";", 
                    escape_double = FALSE, trim_ws = TRUE) # Tygodniowe dane CDPROJECT WIG20
eat_d <- read_delim("~/eat_d.csv", delim = ";", 
                    escape_double = FALSE, trim_ws = TRUE) # Dzienne dane AmRest Holdings SE mWIG40

# Losowanie próbek 1/3 dłuigości 

probka_ew <- sample (eat_w$Zamkniecie, 35)
probka_ed <- sample (eat_d$Zamkniecie, 167)
probka_cd <- sample (cdr_d$Zamkniecie, 167)
probka_cw <- sample (cdr_w$Zamkniecie, 35)

#  Obliczanie stóp zworotu

# stopy zwortu 

sz_e_w <- log(eat_w[2:106,5]) - log(eat_w[1:105,5])
sz_e_d <- log(eat_d[2:501,5]) - log(eat_d[1:500,5])
sz_c_d <- log(cdr_d[2:501,5]) - log(cdr_d[1:500,5])
sz_c_w <- log(cdr_w[2:106,5]) - log(cdr_w[1:105,5])

probka_sz_e_w <- log(probka_ew[2:35]) - log(probka_ew[1:34])
probka_sz_e_d <- log(probka_ed[2:167]) - log(probka_ed[1:166])
probka_sz_c_d <- log(probka_cd[2:167]) - log(probka_cd[1:166])
probka_sz_c_w <- log(probka_cw[2:35]) - log(probka_cw[1:34])

# Stworzenie tabel z wynikami 

wyniki_e_w <- data.frame( eat_w[2:106,1],sz_e_w )
wyniki_e_d <- data.frame(eat_d[2:501,1], sz_e_d  )
wyniki_c_d <- data.frame( cdr_d[2:501,1],sz_c_d )
wyniki_c_w <- data.frame(cdr_w[2:106,1], sz_c_w )

colnames(wyniki_e_w) <- c( "Dzień", "stopy zwortu")
colnames(wyniki_e_d) <- c("Dzień", "stopy zwortu")
colnames(wyniki_c_w) <- c("Dzień","stopy zwortu")
colnames(wyniki_c_d) <- c("Dzień", "stopy zwortu")

# Podstawowe charakterystyki rozkładów  

Średnia <- c( mean(sz_e_w$Zamkniecie), mean(sz_e_d$Zamkniecie), mean (sz_c_w$Zamkniecie), mean(sz_c_d$Zamkniecie))

Odchylenie_stan <- c( sd(sz_e_w$Zamkniecie), sd(sz_e_d$Zamkniecie), sd(sz_c_w$Zamkniecie), sd(sz_c_d$Zamkniecie))

Kurtoza <- c(kurtosis(sz_e_w$Zamkniecie), kurtosis(sz_e_d$Zamkniecie), kurtosis(sz_c_w$Zamkniecie), kurtosis(sz_c_d$Zamkniecie))

Skośność <-  c( skewness(sz_e_w$Zamkniecie), skewness(sz_e_d$Zamkniecie), skewness(sz_c_w$Zamkniecie), skewness(sz_c_d$Zamkniecie))

Statystyki_opisowe <- round (data.frame( Means , Sds , Skewneses, Kurtoses) , 4 )

row.names(Statystyki_opisowe) <- c( " AmRest tygodniowe", "AmRest dzienne", " CDProjekt tygodniowe", "CDProjket dzienne")

# Wizualizacja rozkładów 

boxplot (sz_e_w$Zamkniecie , sz_e_d$Zamkniecie, sz_c_w$Zamkniecie,  sz_c_d$Zamkniecie , names = c( "A tyg", "A d", " C tyg", "C d"))

D <- function(x , kolor) {
  
  ggplot() +
    geom_density(aes(x = x), fill = kolor , col= "black", alpha = 0.6) +
    xlim(-0.3 , 0.3)+
    theme_light() +
    labs (y = NULL,
          x = NULL) 
  
}

D1 <- D(sz_e_w$Zamkniecie, "darkgreen")
D2 <- D( sz_e_d$Zamkniecie , "#9ACD32")
D3 <- D( sz_c_w$Zamkniecie , "navy")
D4 <- D(sz_c_d$Zamkniecie , "steelblue")

plot_grid(D1, D2, D3, D4, align = "hv",
          label_x = 0.1, label_y = 0.95, labels = c(" AmRest tygodniowe", "AmRest dzienne", " CDProjekt tygodniowe", "CDProjket dzienne"), label_size = 13) 
```

```{r}

```

